//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace GameLogic
{
    [DisallowMultipleComponent]
    public class UIBindComponent : MonoBehaviour
    {
        [SerializeField] private List<Component> m_components = new List<Component>();

        public T GetComponent<T>(int index) where T : Component
        {
            if (index < 0 || index >= m_components.Count)
            {
                Debug.LogError("索引超出范围");
                return null;
            }
            T c = m_components[index] as T;

            if (c == null)
            {
                Debug.LogError("没有找到对应类型");
                return null;
            }
            return c;
        }

#if UNITY_EDITOR

        public void AddComponent(Component component)
        {
            if (m_components != null && !m_components.Contains(component))
            {
                m_components.Add(component);
            }
        }

        public void Clear()
        {
            m_components?.Clear();
        }

#endif
    }
}