using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using GameLogic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace DGame
{
    public partial class UIScriptGenerator
    {
        public static bool GenerateManifestCSharpScript(UIBindComponent bindComponent, bool isUniTask)
        {
            List<UIBindingValidationError> errors = UIBindingManifestValidator.Validate(bindComponent);
            if (errors.Count > 0)
            {
                LogValidationErrors(errors);
                return false;
            }

            string signature = UIBindingManifestValidator.CalculateSignature(bindComponent);
            string source = BuildManifestSource(bindComponent, signature, isUniTask);
            if (!TryWriteManifestSource(bindComponent, source))
            {
                return false;
            }

            bindComponent.SetManifestSignature(signature);
            bindComponent.SetGeneratedSignature(signature);
            EditorUtility.SetDirty(bindComponent);
            SaveManifestPrefab(bindComponent.gameObject);
            AssetDatabase.Refresh();
            return true;
        }

        private static void LogValidationErrors(IReadOnlyList<UIBindingValidationError> errors)
        {
            foreach (UIBindingValidationError error in errors)
            {
                Debug.LogError($"[UI Binding Manifest] {error.Message}");
            }
        }

        private static string BuildManifestSource(UIBindComponent bindComponent, string signature, bool isUniTask)
        {
            var builder = new StringBuilder();
            AppendManifestHeader(builder, signature, isUniTask);
            AppendManifestClass(builder, bindComponent);
            AppendManifestConstants(builder, bindComponent.BindingEntries);
            AppendManifestFields(builder, bindComponent.BindingEntries);
            AppendManifestScriptGenerator(builder, bindComponent.BindingEntries);
            builder.AppendLine("\t}").AppendLine("}");
            return builder.ToString();
        }

        private static void AppendManifestHeader(StringBuilder builder, string signature, bool isUniTask)
        {
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine($"// UI Binding Manifest Signature: {signature}");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("using System;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using UnityEngine.UI;");
            builder.AppendLine("using DGame;");
            if (isUniTask)
            {
                builder.AppendLine("using Cysharp.Threading.Tasks;");
            }

            builder.AppendLine().AppendLine($"namespace {UIScriptGeneratorSettings.GetUINameSpace()}").AppendLine("{");
        }

        private static void AppendManifestClass(StringBuilder builder, UIBindComponent bindComponent)
        {
            string className = string.IsNullOrWhiteSpace(bindComponent.ClassName) ? bindComponent.name : bindComponent.ClassName;
            string uiTypeName = GetUITypeName(bindComponent.UITypeName, className, bindComponent.WidgetTypeName,
                bindComponent.DataTypeName);
            builder.AppendLine($"\tpublic partial class {className} : {uiTypeName}").AppendLine("\t{");
            builder.AppendLine("\t\tprivate UIBindComponent m_bindComponent;").AppendLine();
        }

        private static void AppendManifestConstants(StringBuilder builder, IReadOnlyList<UIBindingEntry> entries)
        {
            foreach (UIBindingEntry entry in entries)
            {
                builder.AppendLine($"\t\tprivate const string BINDING_{entry.FieldName} = \"{entry.BindingId}\";");
            }

            builder.AppendLine();
        }

        private static void AppendManifestFields(StringBuilder builder, IReadOnlyList<UIBindingEntry> entries)
        {
            foreach (UIBindingEntry entry in entries)
            {
                builder.AppendLine($"\t\tprivate {GetFieldTypeName(entry)} {entry.FieldName};");
            }

            builder.AppendLine();
        }

        private static void AppendManifestScriptGenerator(StringBuilder builder, IReadOnlyList<UIBindingEntry> entries)
        {
            builder.AppendLine("\t\tprotected override void ScriptGenerator()").AppendLine("\t\t{");
            builder.AppendLine("\t\t\tm_bindComponent = gameObject.GetComponent<UIBindComponent>();");
            builder.AppendLine("\t\t\tif (m_bindComponent == null)");
            builder.AppendLine("\t\t\t{");
            builder.AppendLine("\t\t\t\tthrow new InvalidOperationException(\"UI Binding Manifest组件缺失。\");");
            builder.AppendLine("\t\t\t}");
            foreach (UIBindingEntry entry in entries)
            {
                builder.AppendLine($"\t\t\t{BuildBindingStatement(entry)}");
                AppendEventStatement(builder, entry);
            }

            builder.AppendLine("\t\t}").AppendLine();
        }

        private static string BuildBindingStatement(UIBindingEntry entry)
        {
            string bindingId = $"BINDING_{entry.FieldName}";
            return entry.Kind switch
            {
                UIBindingKind.GameObject => $"{entry.FieldName} = m_bindComponent.GetRequired<RectTransform>({bindingId}).gameObject;",
                UIBindingKind.Widget => $"{entry.FieldName} = CreateWidget<{GetFieldTypeName(entry)}>(m_bindComponent.GetRequired<RectTransform>({bindingId}).gameObject);",
                _ => $"{entry.FieldName} = m_bindComponent.GetRequired<{GetFieldTypeName(entry)}>({bindingId});",
            };
        }

        private static void AppendEventStatement(StringBuilder builder, UIBindingEntry entry)
        {
            if (!entry.GenerateUnityEvent)
            {
                return;
            }

            string statement = entry.EventKind switch
            {
                UIBindingEventKind.Click => $"{entry.FieldName}.onClick.AddListener({entry.EventHandlerName});",
                UIBindingEventKind.ToggleValueChanged => $"{entry.FieldName}.onValueChanged.AddListener({entry.EventHandlerName});",
                UIBindingEventKind.SliderValueChanged => $"{entry.FieldName}.onValueChanged.AddListener({entry.EventHandlerName});",
                _ => string.Empty,
            };
            builder.AppendLine($"\t\t\t{statement}");
        }

        private static string GetFieldTypeName(UIBindingEntry entry)
        {
            if (entry.Kind == UIBindingKind.GameObject)
            {
                return "GameObject";
            }

            Type type = Type.GetType(entry.ExpectedTypeName);
            return type == null ? entry.ExpectedTypeName : type.Name;
        }

        private static bool TryWriteManifestSource(UIBindComponent bindComponent, string source)
        {
            string className = string.IsNullOrWhiteSpace(bindComponent.ClassName) ? bindComponent.name : bindComponent.ClassName;
            string filePath = Path.Combine(bindComponent.GenCodePath, className + "_Gen.g.cs");
            try
            {
                Directory.CreateDirectory(bindComponent.GenCodePath);
                File.WriteAllText(filePath, source, Encoding.UTF8);
                return true;
            }
            catch (Exception exception)
            {
                Debug.LogError($"[UI Binding Manifest] 写入生成文件失败: {filePath}\n{exception}");
                return false;
            }
        }

        private static void SaveManifestPrefab(GameObject gameObject)
        {
            if (IsInPrefabMode(gameObject))
            {
                SavePrefabChanges(gameObject);
                return;
            }

            EditorSceneManager.MarkSceneDirty(gameObject.scene);
        }
    }
}
