using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using GameLogic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace DGame
{
    public partial class UIScriptGenerator
    {
        private const string ITEM_LOGIC_FOLDER_NAME = "Item";

        public static bool GenerateManifestCSharpScript(UIBindComponent bindComponent, bool isUniTask)
        {
            List<UIBindingValidationError> errors = UIBindingManifestValidator.Validate(bindComponent);
            if (errors.Count > 0)
            {
                LogValidationErrors(errors);
                return false;
            }

            string signature = UIBindingManifestValidator.CalculateSignature(bindComponent);
            string source = BuildManifestSource(bindComponent, signature, isUniTask);
            if (!TryGenerateManifestLogicClass(bindComponent))
            {
                return false;
            }

            if (!TryWriteManifestSource(bindComponent, source))
            {
                return false;
            }

            bindComponent.SetManifestSignature(signature);
            bindComponent.SetGeneratedSignature(signature);
            EditorUtility.SetDirty(bindComponent);
            SaveManifestPrefab(bindComponent.gameObject);
            AssetDatabase.Refresh();
            return true;
        }

        private static void LogValidationErrors(IReadOnlyList<UIBindingValidationError> errors)
        {
            foreach (UIBindingValidationError error in errors)
            {
                Debug.LogError($"[UI Binding Manifest] {error.Message}");
            }
        }

        private static string BuildManifestSource(UIBindComponent bindComponent, string signature, bool isUniTask)
        {
            var builder = new StringBuilder();
            AppendManifestHeader(builder, signature, isUniTask);
            AppendManifestClass(builder, bindComponent);
            AppendManifestConstants(builder, bindComponent.BindingEntries);
            AppendManifestFields(builder, bindComponent.BindingEntries);
            AppendManifestScriptGenerator(builder, bindComponent.BindingEntries);
            builder.AppendLine("\t}").AppendLine("}");
            return builder.ToString();
        }

        private static void AppendManifestHeader(StringBuilder builder, string signature, bool isUniTask)
        {
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine($"// UI Binding Manifest Signature: {signature}");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("using System;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using UnityEngine.UI;");
            builder.AppendLine("using DGame;");
            if (isUniTask)
            {
                builder.AppendLine("using Cysharp.Threading.Tasks;");
            }

            builder.AppendLine().AppendLine($"namespace {UIScriptGeneratorSettings.GetUINameSpace()}").AppendLine("{");
        }

        private static void AppendManifestClass(StringBuilder builder, UIBindComponent bindComponent)
        {
            string className = string.IsNullOrWhiteSpace(bindComponent.ClassName) ? bindComponent.name : bindComponent.ClassName;
            string uiTypeName = GetUITypeName(bindComponent.UITypeName, className, bindComponent.WidgetTypeName,
                bindComponent.DataTypeName);
            builder.AppendLine($"\tpublic class {GetGeneratedClassName(className)} : {uiTypeName}").AppendLine("\t{");
            builder.AppendLine("\t\tprivate UIBindComponent m_bindComponent;").AppendLine();
        }

        internal static string GetGeneratedClassName(string className) => $"{className}Auto";

        private static void AppendManifestConstants(StringBuilder builder, IReadOnlyList<UIBindingEntry> entries)
        {
            foreach (UIBindingEntry entry in entries)
            {
                builder.AppendLine($"\t\tprivate const string BINDING_{entry.FieldName} = \"{entry.BindingId}\";");
            }

            builder.AppendLine();
        }

        private static void AppendManifestFields(StringBuilder builder, IReadOnlyList<UIBindingEntry> entries)
        {
            foreach (UIBindingEntry entry in entries)
            {
                builder.AppendLine($"\t\tprotected {GetFieldTypeName(entry)} {entry.FieldName};");
            }

            builder.AppendLine();
        }

        private static void AppendManifestScriptGenerator(StringBuilder builder, IReadOnlyList<UIBindingEntry> entries)
        {
            builder.AppendLine("\t\tprotected override void ScriptGenerator()").AppendLine("\t\t{");
            builder.AppendLine("\t\t\tm_bindComponent = gameObject.GetComponent<UIBindComponent>();");
            builder.AppendLine("\t\t\tif (m_bindComponent == null)");
            builder.AppendLine("\t\t\t{");
            builder.AppendLine("\t\t\t\tthrow new InvalidOperationException(\"UI Binding Manifest组件缺失。\");");
            builder.AppendLine("\t\t\t}");
            foreach (UIBindingEntry entry in entries)
            {
                builder.AppendLine($"\t\t\t{BuildBindingStatement(entry)}");
                AppendEventStatement(builder, entry);
            }

            builder.AppendLine("\t\t}").AppendLine();
            AppendEventHandlers(builder, entries);
        }

        private static void AppendEventHandlers(StringBuilder builder, IReadOnlyList<UIBindingEntry> entries)
        {
            foreach (UIBindingEntry entry in entries)
            {
                if (!entry.GenerateUnityEvent)
                {
                    continue;
                }

                string parameters = entry.EventKind switch
                {
                    UIBindingEventKind.ToggleValueChanged => "bool isOn",
                    UIBindingEventKind.SliderValueChanged => "float value",
                    UIBindingEventKind.DropdownValueChanged => "int value",
                    _ => string.Empty,
                };
                builder.AppendLine($"\t\tprotected virtual void {entry.EventHandlerName}({parameters})")
                    .AppendLine("\t\t{")
                    .AppendLine("\t\t}")
                    .AppendLine();
            }
        }

        private static string BuildBindingStatement(UIBindingEntry entry)
        {
            string bindingId = $"BINDING_{entry.FieldName}";
            return entry.Kind switch
            {
                UIBindingKind.GameObject => $"{entry.FieldName} = m_bindComponent.GetRequired<RectTransform>({bindingId}).gameObject;",
                UIBindingKind.Widget => $"{entry.FieldName} = CreateWidget<{GetFieldTypeName(entry)}>(m_bindComponent.GetRequired<RectTransform>({bindingId}).gameObject);",
                _ => $"{entry.FieldName} = m_bindComponent.GetRequired<{GetFieldTypeName(entry)}>({bindingId});",
            };
        }

        private static void AppendEventStatement(StringBuilder builder, UIBindingEntry entry)
        {
            if (!entry.GenerateUnityEvent)
            {
                return;
            }

            string statement = entry.EventKind switch
            {
                UIBindingEventKind.Click => $"{entry.FieldName}.onClick.AddListener({entry.EventHandlerName});",
                UIBindingEventKind.ToggleValueChanged => $"{entry.FieldName}.onValueChanged.AddListener({entry.EventHandlerName});",
                UIBindingEventKind.SliderValueChanged => $"{entry.FieldName}.onValueChanged.AddListener({entry.EventHandlerName});",
                UIBindingEventKind.DropdownValueChanged => $"{entry.FieldName}.onValueChanged.AddListener({entry.EventHandlerName});",
                _ => string.Empty,
            };
            builder.AppendLine($"\t\t\t{statement}");
        }

        private static string GetFieldTypeName(UIBindingEntry entry)
        {
            if (entry.Kind == UIBindingKind.GameObject)
            {
                return "GameObject";
            }

            Type type = Type.GetType(entry.ExpectedTypeName);
            return type == null ? entry.ExpectedTypeName : type.Name;
        }

        private static bool TryWriteManifestSource(UIBindComponent bindComponent, string source)
        {
            string className = string.IsNullOrWhiteSpace(bindComponent.ClassName) ? bindComponent.name : bindComponent.ClassName;
            string outputDirectory = UIScriptGeneratorSettings.GetGenCodePath();
            if (string.IsNullOrWhiteSpace(outputDirectory))
            {
                Debug.LogError("[UI Binding Manifest] 项目配置中的组件代码生成路径为空。");
                return false;
            }

            string filePath = Path.Combine(outputDirectory, className + "Auto_Gen.g.cs");
            try
            {
                Directory.CreateDirectory(outputDirectory);
                File.WriteAllText(filePath, source, Encoding.UTF8);
                return true;
            }
            catch (Exception exception)
            {
                Debug.LogError($"[UI Binding Manifest] 写入生成文件失败: {filePath}\n{exception}");
                return false;
            }
        }

        /// <summary>
        /// 生成继承自动基类的业务逻辑骨架；已有文件只校验位置，不执行覆盖。
        /// </summary>
        internal static bool TryGenerateManifestLogicClass(UIBindComponent bindComponent)
        {
            string className = GetBindingClassName(bindComponent);
            string logicPath = GetLogicCodePath(className, bindComponent.UITypeName);
            if (!ValidateLogicFileLocation(className, logicPath))
            {
                return false;
            }

            if (File.Exists(logicPath))
            {
                return true;
            }

            string source = BuildManifestLogicSource(bindComponent, className);
            Directory.CreateDirectory(Path.GetDirectoryName(logicPath));
            File.WriteAllText(logicPath, source, Encoding.UTF8);
            Debug.Log($"[UI Logic Generator] 已生成业务逻辑类: {logicPath}");
            return true;
        }

        internal static string GetLogicCodePath(string className, string uiTypeName)
        {
            string root = UIScriptGeneratorSettings.GetImpCodePath();
            if (string.IsNullOrWhiteSpace(root))
            {
                throw new InvalidOperationException("项目配置中的实现类代码路径为空。");
            }

            string directory = IsWindowType(uiTypeName)
                ? Path.Combine(root, className)
                : Path.Combine(root, ITEM_LOGIC_FOLDER_NAME);
            return NormalizePath(Path.Combine(directory, className + ".cs"));
        }

        internal static string[] FindLogicCodeFiles(string className)
        {
            string root = UIScriptGeneratorSettings.GetImpCodePath();
            if (string.IsNullOrWhiteSpace(root) || !Directory.Exists(root))
            {
                return Array.Empty<string>();
            }

            return Directory.GetFiles(root, className + ".cs", SearchOption.AllDirectories)
                .Select(NormalizePath)
                .OrderBy(path => path, StringComparer.Ordinal)
                .ToArray();
        }

        internal static bool ValidateLogicFileLocation(string className, string expectedPath)
        {
            string[] existingFiles = FindLogicCodeFiles(className);
            if (existingFiles.Length == 0)
            {
                return true;
            }

            if (existingFiles.Length == 1 && PathsEqual(existingFiles[0], expectedPath))
            {
                return true;
            }

            Debug.LogError(CreateLogicLocationError(className, expectedPath, existingFiles));
            return false;
        }

        internal static string CreateLogicLocationError(string className, string expectedPath,
            IReadOnlyList<string> existingFiles)
        {
            string locations = string.Join(", ", existingFiles);
            return $"[UI Logic Generator] {className} 逻辑类目录不符合规则。当前: {locations}; 目标: {expectedPath}";
        }

        internal static string GetBindingClassName(UIBindComponent bindComponent)
        {
            return string.IsNullOrWhiteSpace(bindComponent.ClassName)
                ? bindComponent.name
                : bindComponent.ClassName;
        }

        private static string BuildManifestLogicSource(UIBindComponent bindComponent, string className)
        {
            var builder = new StringBuilder();
            builder.AppendLine($"namespace {UIScriptGeneratorSettings.GetUINameSpace()}")
                .AppendLine("{")
                .AppendLine("\t/// <summary>")
                .AppendLine($"\t/// {className} 的 UI 业务逻辑。")
                .AppendLine("\t/// </summary>")
                .AppendLine($"\tpublic class {className} : {GetGeneratedClassName(className)}")
                .AppendLine("\t{");
            AppendLogicEventHandlers(builder, bindComponent.BindingEntries);
            builder.AppendLine("\t}").AppendLine("}");
            return builder.ToString();
        }

        private static void AppendLogicEventHandlers(StringBuilder builder, IReadOnlyList<UIBindingEntry> entries)
        {
            foreach (UIBindingEntry entry in entries)
            {
                if (!entry.GenerateUnityEvent)
                {
                    continue;
                }

                string parameters = GetEventParameters(entry.EventKind);
                builder.AppendLine($"\t\tprotected override void {entry.EventHandlerName}({parameters})")
                    .AppendLine("\t\t{")
                    .AppendLine("\t\t}")
                    .AppendLine();
            }
        }

        private static string GetEventParameters(UIBindingEventKind eventKind)
        {
            return eventKind switch
            {
                UIBindingEventKind.ToggleValueChanged => "bool isOn",
                UIBindingEventKind.SliderValueChanged => "float value",
                UIBindingEventKind.DropdownValueChanged => "int value",
                _ => string.Empty,
            };
        }

        private static bool IsWindowType(string uiTypeName)
        {
            return string.Equals(uiTypeName, nameof(UIWindow), StringComparison.Ordinal);
        }

        private static bool PathsEqual(string left, string right)
        {
            return string.Equals(NormalizePath(left), NormalizePath(right), StringComparison.OrdinalIgnoreCase);
        }

        private static string NormalizePath(string path) => path?.Replace('\\', '/');

        private static void SaveManifestPrefab(GameObject gameObject)
        {
            if (IsInPrefabMode(gameObject))
            {
                SavePrefabChanges(gameObject);
                return;
            }

            EditorSceneManager.MarkSceneDirty(gameObject.scene);
        }
    }
}
