
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum ActivityOpenType
    {
        /// <summary>
        /// 不开启
        /// </summary>
        ACTIVITY_OPEN_TYPE_CLOSE = 0,
        /// <summary>
        /// 固定开启
        /// </summary>
        ACTIVITY_OPEN_TYPE_FIXED = 1,
        /// <summary>
        /// 指定时间开启
        /// </summary>
        ACTIVITY_OPEN_TYPE_TIME = 2,
        /// <summary>
        /// 开服时间
        /// </summary>
        ACTIVITY_OPEN_TYPE_SVR_OPEN_TIME = 3,
        /// <summary>
        /// 合服时间
        /// </summary>
        ACTIVITY_OPEN_TYPE_SVR_MEAGE_TIME = 4,
        /// <summary>
        /// 每日固定时间
        /// </summary>
        ACTIVITY_OPEN_TYPE_SVR_DAILY_TIME = 5,
        /// <summary>
        /// 每周固定时间
        /// </summary>
        ACTIVITY_OPEN_TYPE_SVR_WEEK_TIME = 6,
        /// <summary>
        /// 每周固定时间段
        /// </summary>
        ACTIVITY_OPEN_TYPE_SVR_WEEK_DURATION_TIME = 7,
        /// <summary>
        /// 创角天数
        /// </summary>
        ACTIVITY_OPEN_TYPE_CREATE_ROLE_DAY = 8,
        /// <summary>
        /// 按照当前创角时间开启活动 精确到秒
        /// </summary>
        ACTIVITY_OPEN_TYPE_CREATE_ROLE_DAY_SECONDS = 9,
    }

} 

