
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class ChapterHangDropItem : Luban.BeanBase
{
    public ChapterHangDropItem() { }
    
    public ChapterHangDropItem(ByteBuf _buf) 
    {
        ItemID = _buf.ReadInt();
        Num = _buf.ReadInt();
    }

    public static ChapterHangDropItem DeserializeChapterHangDropItem(ByteBuf _buf)
    {
        return new ChapterHangDropItem(_buf);
    }

    /// <summary>
    /// 挂机道具类型
    /// </summary>
    public int ItemID;
    /// <summary>
    /// 数量
    /// </summary>
    public int Num;

    public const int __ID__ = 387067393;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref ChapterHangDropItem other)
    {
        if (other == null)
        {
            other = new ChapterHangDropItem();
        }
        other.ItemID = ItemID;
        other.Num = Num;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "Num:" + Num + ","
        + "}";
    }
}
}

