
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideType
    {
        /// <summary>
        /// 强引导
        /// </summary>
        ForceGuide = 0,
        /// <summary>
        /// 弱引导
        /// </summary>
        WeakGuide = 1,
    }

} 

