
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideTipPlacement
    {
        /// <summary>
        /// 屏幕中央
        /// </summary>
        ScreenCenter = 0,
        /// <summary>
        /// 目标上方
        /// </summary>
        AboveTarget = 1,
        /// <summary>
        /// 目标下方
        /// </summary>
        BelowTarget = 2,
    }

} 

