
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideState
    {
        /// <summary>
        /// 未就绪
        /// </summary>
        NotReady = 0,
        /// <summary>
        /// 空闲
        /// </summary>
        Idle = 1,
        /// <summary>
        /// 解析目标
        /// </summary>
        ResolvingTarget = 2,
        /// <summary>
        /// 展示中
        /// </summary>
        Presenting = 3,
        /// <summary>
        /// 等待中
        /// </summary>
        Waiting = 4,
        /// <summary>
        /// 已暂停
        /// </summary>
        Paused = 5,
    }

} 

