
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideInputMode
    {
        /// <summary>
        /// 全部拦截
        /// </summary>
        BlockAll = 0,
        /// <summary>
        /// 目标透传
        /// </summary>
        PassThroughTarget = 1,
        /// <summary>
        /// 全部放行
        /// </summary>
        AllowAll = 2,
    }

} 

