
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideResumePolicy
    {
        /// <summary>
        /// 重启引导
        /// </summary>
        RestartGuide = 0,
        /// <summary>
        /// 恢复步骤
        /// </summary>
        ResumeStep = 1,
        /// <summary>
        /// 不恢复
        /// </summary>
        DoNotResume = 2,
    }

} 

