
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideArrowMoveType
    {
        /// <summary>
        /// 不显示
        /// </summary>
        None = 0,
        /// <summary>
        /// 中间移动到目标位置
        /// </summary>
        Target = 1,
        /// <summary>
        /// 自定义移动方向
        /// </summary>
        CustomMove = 2,
    }

} 

