
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideStepType
    {
        /// <summary>
        /// 说明
        /// </summary>
        Explain = 0,
        /// <summary>
        /// 点击目标
        /// </summary>
        ClickTarget = 1,
        /// <summary>
        /// 任意点击
        /// </summary>
        ClickAnywhere = 2,
        /// <summary>
        /// 等待事件
        /// </summary>
        WaitEvent = 3,
        /// <summary>
        /// 延时
        /// </summary>
        Delay = 4,
        /// <summary>
        /// 拖拽提示
        /// </summary>
        DragHint = 5,
        /// <summary>
        /// 自定义动作
        /// </summary>
        CustomAction = 6,
    }

} 

