
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideSkipScope
    {
        /// <summary>
        /// 当前引导
        /// </summary>
        Guide = 0,
        /// <summary>
        /// 整个引导组
        /// </summary>
        Group = 1,
    }

} 

