
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideFailurePolicy
    {
        /// <summary>
        /// 重试
        /// </summary>
        Retry = 0,
        /// <summary>
        /// 跳过步骤
        /// </summary>
        SkipStep = 1,
        /// <summary>
        /// 中止引导
        /// </summary>
        AbortGuide = 2,
    }

} 

