
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    public enum EGuideMaskShape
    {
        /// <summary>
        /// 无遮罩孔
        /// </summary>
        None = 0,
        /// <summary>
        /// 圆形
        /// </summary>
        Circle = 1,
        /// <summary>
        /// 矩形
        /// </summary>
        Rectangle = 2,
        /// <summary>
        /// 圆角矩形
        /// </summary>
        RoundedRectangle = 3,
    }

} 

