
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class FuncOpenConfig : Luban.BeanBase
{
    public FuncOpenConfig() { }
    
    public FuncOpenConfig(ByteBuf _buf) 
    {
        FuncId = _buf.ReadInt();
        FuncNameId = _buf.ReadInt();
        FuncIcon = _buf.ReadString();
        FuncSelectIcon = _buf.ReadString();
        FuncNoSelectIcon = _buf.ReadString();
        FuncLockIcon = _buf.ReadString();
        OpenLevel = _buf.ReadInt();
        CreateRoleDay = _buf.ReadInt();
        OpenChapter = _buf.ReadInt();
        ParentFuncId = _buf.ReadInt();
        UseOpenTips = _buf.ReadBool();
        OpenTipsId = _buf.ReadInt();
        NoOpenTipsId = _buf.ReadInt();
    }

    public static FuncOpenConfig DeserializeFuncOpenConfig(ByteBuf _buf)
    {
        return new FuncOpenConfig(_buf);
    }

    /// <summary>
    /// 系统ID
    /// </summary>
    public int FuncId;
    /// <summary>
    /// 系统名称ID
    /// </summary>
    public int FuncNameId;
    /// <summary>
    /// 系统图标
    /// </summary>
    public string FuncIcon;
    /// <summary>
    /// 系统选中图标
    /// </summary>
    public string FuncSelectIcon;
    /// <summary>
    /// 系统未选中图标
    /// </summary>
    public string FuncNoSelectIcon;
    /// <summary>
    /// 系统未解锁图标
    /// </summary>
    public string FuncLockIcon;
    /// <summary>
    /// 开启等级
    /// </summary>
    public int OpenLevel;
    /// <summary>
    /// 创角天数限制
    /// </summary>
    public int CreateRoleDay;
    /// <summary>
    /// 通关章节ID
    /// </summary>
    public int OpenChapter;
    /// <summary>
    /// 所属父系统
    /// </summary>
    public int ParentFuncId;
    /// <summary>
    /// 开启提示
    /// </summary>
    public bool UseOpenTips;
    /// <summary>
    /// 开启提示文本ID
    /// </summary>
    public int OpenTipsId;
    /// <summary>
    /// 未开启提示文本ID
    /// </summary>
    public int NoOpenTipsId;

    public const int __ID__ = 391142448;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref FuncOpenConfig other)
    {
        if (other == null)
        {
            other = new FuncOpenConfig();
        }
        other.FuncId = FuncId;
        other.FuncNameId = FuncNameId;
        other.FuncIcon = FuncIcon;
        other.FuncSelectIcon = FuncSelectIcon;
        other.FuncNoSelectIcon = FuncNoSelectIcon;
        other.FuncLockIcon = FuncLockIcon;
        other.OpenLevel = OpenLevel;
        other.CreateRoleDay = CreateRoleDay;
        other.OpenChapter = OpenChapter;
        other.ParentFuncId = ParentFuncId;
        other.UseOpenTips = UseOpenTips;
        other.OpenTipsId = OpenTipsId;
        other.NoOpenTipsId = NoOpenTipsId;
    }
    
    public override string ToString()
    {
        return "{ "
        + "FuncId:" + FuncId + ","
        + "FuncNameId:" + FuncNameId + ","
        + "FuncIcon:" + FuncIcon + ","
        + "FuncSelectIcon:" + FuncSelectIcon + ","
        + "FuncNoSelectIcon:" + FuncNoSelectIcon + ","
        + "FuncLockIcon:" + FuncLockIcon + ","
        + "OpenLevel:" + OpenLevel + ","
        + "CreateRoleDay:" + CreateRoleDay + ","
        + "OpenChapter:" + OpenChapter + ","
        + "ParentFuncId:" + ParentFuncId + ","
        + "UseOpenTips:" + UseOpenTips + ","
        + "OpenTipsId:" + OpenTipsId + ","
        + "NoOpenTipsId:" + NoOpenTipsId + ","
        + "}";
    }
}
}

