
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class GetWayConfig : Luban.BeanBase
{
    public GetWayConfig() { }
    
    public GetWayConfig(ByteBuf _buf) 
    {
        WayId = _buf.ReadInt();
        FuncId = _buf.ReadInt();
        ActivityId = _buf.ReadInt();
        WayName = _buf.ReadString();
        EventType = _buf.ReadByte();
        {int __n0 = _buf.ReadSize(); ParameterList = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ParameterList[__index0] = __e0;}}
    }

    public static GetWayConfig DeserializeGetWayConfig(ByteBuf _buf)
    {
        return new GetWayConfig(_buf);
    }

    /// <summary>
    /// 途径ID
    /// </summary>
    public int WayId;
    /// <summary>
    /// 系统ID
    /// </summary>
    public int FuncId;
    /// <summary>
    /// 活动ID
    /// </summary>
    public int ActivityId;
    /// <summary>
    /// 名称
    /// </summary>
    public string WayName;
    /// <summary>
    /// 类型
    /// </summary>
    public byte EventType;
    /// <summary>
    /// 参数数组
    /// </summary>
    public int[] ParameterList;

    public const int __ID__ = -892284805;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref GetWayConfig other)
    {
        if (other == null)
        {
            other = new GetWayConfig();
        }
        other.WayId = WayId;
        other.FuncId = FuncId;
        other.ActivityId = ActivityId;
        other.WayName = WayName;
        other.EventType = EventType;
        other.ParameterList = ParameterList;
    }
    
    public override string ToString()
    {
        return "{ "
        + "WayId:" + WayId + ","
        + "FuncId:" + FuncId + ","
        + "ActivityId:" + ActivityId + ","
        + "WayName:" + WayName + ","
        + "EventType:" + EventType + ","
        + "ParameterList:" + Luban.StringUtil.CollectionToString(ParameterList) + ","
        + "}";
    }
}
}

