
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 引导参数
/// </summary>
public partial struct GuideStepParam
{
    
    public GuideStepParam(ByteBuf _buf) 
    {
        IntParam = _buf.ReadInt();
        StringParam1 = _buf.ReadString();
        StringParam2 = _buf.ReadString();
    }

    public static GuideStepParam DeserializeGuideStepParam(ByteBuf _buf)
    {
        return new GuideStepParam(_buf);
    }

    /// <summary>
    /// Int类型引导参数
    /// </summary>
    public int IntParam;
    /// <summary>
    /// String类型引导参数1
    /// </summary>
    public string StringParam1;
    /// <summary>
    /// String类型引导参数2
    /// </summary>
    public string StringParam2;


    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref GuideStepParam other)
    {
        other.IntParam = IntParam;
        other.StringParam1 = StringParam1;
        other.StringParam2 = StringParam2;
    }
    
    public override string ToString()
    {
        return "{ "
        + "IntParam:" + IntParam + ","
        + "StringParam1:" + StringParam1 + ","
        + "StringParam2:" + StringParam2 + ","
        + "}";
    }
}
}

