
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class ModelConfig : Luban.BeanBase
{
    public ModelConfig() { }
    
    public ModelConfig(ByteBuf _buf) 
    {
        ModelID = _buf.ReadInt();
        UISpineLocation = _buf.ReadString();
        ModelLocation = _buf.ReadString();
    }

    public static ModelConfig DeserializeModelConfig(ByteBuf _buf)
    {
        return new ModelConfig(_buf);
    }

    /// <summary>
    /// 模型ID
    /// </summary>
    public int ModelID;
    /// <summary>
    /// UISpine可寻址地址
    /// </summary>
    public string UISpineLocation;
    /// <summary>
    /// Model可寻址地址
    /// </summary>
    public string ModelLocation;

    public const int __ID__ = 1694060459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref ModelConfig other)
    {
        if (other == null)
        {
            other = new ModelConfig();
        }
        other.ModelID = ModelID;
        other.UISpineLocation = UISpineLocation;
        other.ModelLocation = ModelLocation;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ModelID:" + ModelID + ","
        + "UISpineLocation:" + UISpineLocation + ","
        + "ModelLocation:" + ModelLocation + ","
        + "}";
    }
}
}

