
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    /// <summary>
    /// 玩家性别体型
    /// </summary>
    public enum RoleBodyType
    {
        /// <summary>
        /// 无定以体型
        /// </summary>
        ROLE_BODY_NONE = 0,
        /// <summary>
        /// 男性体型
        /// </summary>
        ROLE_BODY_MALE = 1,
        /// <summary>
        /// 女性体型
        /// </summary>
        ROLE_BODY_FEMALE = 2,
    }

} 

