
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 大小
/// </summary>
public partial struct Size
{
    
    public Size(ByteBuf _buf) 
    {
        Width = _buf.ReadFloat();
        Height = _buf.ReadFloat();
    }

    public static Size DeserializeSize(ByteBuf _buf)
    {
        return new Size(_buf);
    }

    /// <summary>
    /// 宽
    /// </summary>
    public float Width;
    /// <summary>
    /// 高
    /// </summary>
    public float Height;


    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref Size other)
    {
        other.Width = Width;
        other.Height = Height;
    }
    
    public override string ToString()
    {
        return "{ "
        + "Width:" + Width + ","
        + "Height:" + Height + ","
        + "}";
    }
}
}

