
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 活动开启配置表
/// </summary>
public partial class TbActivityOpenConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ActivityOpenConfig> _dataMap;
    private readonly System.Collections.Generic.List<ActivityOpenConfig> _dataList;
    
    public TbActivityOpenConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ActivityOpenConfig>(n);
        _dataList = new System.Collections.Generic.List<ActivityOpenConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ActivityOpenConfig _v;
            _v = global::GameProto.ActivityOpenConfig.DeserializeActivityOpenConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ActivityId, _v);
        }
    }

    #region 静态访问

    private static TbActivityOpenConfig m_instance;
    public static TbActivityOpenConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbActivityOpenConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out ActivityOpenConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static ActivityOpenConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, ActivityOpenConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<ActivityOpenConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, ActivityOpenConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<ActivityOpenConfig> dataList => _dataList;

    public ActivityOpenConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ActivityOpenConfig Get(int key) => _dataMap[key];
    public ActivityOpenConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

