
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 章节配置表
/// </summary>
public partial class TbChapterConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ChapterConfig> _dataMap;
    private readonly System.Collections.Generic.List<ChapterConfig> _dataList;
    
    public TbChapterConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ChapterConfig>(n);
        _dataList = new System.Collections.Generic.List<ChapterConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ChapterConfig _v;
            _v = global::GameProto.ChapterConfig.DeserializeChapterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ChapterID, _v);
        }
    }

    #region 静态访问

    private static TbChapterConfig m_instance;
    public static TbChapterConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbChapterConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out ChapterConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static ChapterConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, ChapterConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<ChapterConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, ChapterConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<ChapterConfig> dataList => _dataList;

    public ChapterConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ChapterConfig Get(int key) => _dataMap[key];
    public ChapterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

