
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 功能参数配置表
/// </summary>
public partial class TbFuncParamConfig
{

     private readonly FuncParamConfig _data;

     public FuncParamConfig Data => _data;

    public TbFuncParamConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameProto.FuncParamConfig.DeserializeFuncParamConfig(_buf);
    }

    #region 静态访问

    private static TbFuncParamConfig m_instance;
    public static TbFuncParamConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbFuncParamConfig : m_instance;

    #endregion

    /// <summary>
    /// 账号Token公钥
    /// </summary>
     public static string AccountTokenPublicKeyPem => Instance._data.AccountTokenPublicKeyPem;
    /// <summary>
    /// 账号Token私钥
    /// </summary>
     public static string AccountTokenPrivateKeyPem => Instance._data.AccountTokenPrivateKeyPem;
    /// <summary>
    /// 账号Token过期时间(毫秒)
    /// </summary>
     public static int AccountTokenExpireTime => Instance._data.AccountTokenExpireTime;
    /// <summary>
    /// 发证者
    /// </summary>
     public static string AccountValidIssuer => Instance._data.AccountValidIssuer;
    /// <summary>
    /// 受众
    /// </summary>
     public static string AccountValidAudience => Instance._data.AccountValidAudience;
    /// <summary>
    /// 注册Session的延迟销毁时间(毫秒)(短链接)
    /// </summary>
     public static int AccountRegisterSessionLifeTime => Instance._data.AccountRegisterSessionLifeTime;
    /// <summary>
    /// 记录服务器最近登录最大个数
    /// </summary>
     public static int RecentServerMaxCount => Instance._data.RecentServerMaxCount;
    /// <summary>
    /// 断线重连时旧的Session生命周期(毫秒)
    /// </summary>
     public static int OldSessionLifeTime => Instance._data.OldSessionLifeTime;
    /// <summary>
    /// 延迟下线时间(毫秒)
    /// </summary>
     public static int DelayOfflineTime => Instance._data.DelayOfflineTime;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

