
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 功能参数配置表
/// </summary>
public partial class TbFuncParamConfig
{

     private readonly FuncParamConfig _data;

     public FuncParamConfig Data => _data;

    public TbFuncParamConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameProto.FuncParamConfig.DeserializeFuncParamConfig(_buf);
    }


    /// <summary>
    /// 账号Token公钥
    /// </summary>
     public string AccountTokenPublicKeyPem => _data.AccountTokenPublicKeyPem;
    /// <summary>
    /// 账号Token私钥
    /// </summary>
     public string AccountTokenPrivateKeyPem => _data.AccountTokenPrivateKeyPem;
    /// <summary>
    /// 账号Token过期时间(毫秒)
    /// </summary>
     public int AccountTokenExpireTime => _data.AccountTokenExpireTime;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

