
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 系统开放配置表
/// </summary>
public partial class TbFuncOpenConfig
{
    private readonly System.Collections.Generic.Dictionary<int, FuncOpenConfig> _dataMap;
    private readonly System.Collections.Generic.List<FuncOpenConfig> _dataList;
    
    public TbFuncOpenConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, FuncOpenConfig>(n);
        _dataList = new System.Collections.Generic.List<FuncOpenConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            FuncOpenConfig _v;
            _v = global::GameProto.FuncOpenConfig.DeserializeFuncOpenConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FuncId, _v);
        }
    }

    #region 静态访问

    private static TbFuncOpenConfig m_instance;
    public static TbFuncOpenConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbFuncOpenConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out FuncOpenConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static FuncOpenConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, FuncOpenConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<FuncOpenConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, FuncOpenConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<FuncOpenConfig> dataList => _dataList;

    public FuncOpenConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public FuncOpenConfig Get(int key) => _dataMap[key];
    public FuncOpenConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

