
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// GM配置表
/// </summary>
public partial class TbGmConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GmConfig> _dataMap;
    private readonly System.Collections.Generic.List<GmConfig> _dataList;
    
    public TbGmConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GmConfig>(n);
        _dataList = new System.Collections.Generic.List<GmConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GmConfig _v;
            _v = global::GameProto.GmConfig.DeserializeGmConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GmID, _v);
        }
    }

    #region 静态访问

    private static TbGmConfig m_instance;
    public static TbGmConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbGmConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out GmConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static GmConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, GmConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<GmConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, GmConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<GmConfig> dataList => _dataList;

    public GmConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GmConfig Get(int key) => _dataMap[key];
    public GmConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

