
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 新手引导步骤配置表
/// </summary>
public partial class TbGuideStepConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GuideStepConfig> _dataMap;
    private readonly System.Collections.Generic.List<GuideStepConfig> _dataList;
    
    public TbGuideStepConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GuideStepConfig>(n);
        _dataList = new System.Collections.Generic.List<GuideStepConfig>(n);
        _groupedDataMap = new System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<GuideStepConfig>>();
        for(int i = n ; i > 0 ; --i)
        {
            GuideStepConfig _v;
            _v = global::GameProto.GuideStepConfig.DeserializeGuideStepConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GuideId, _v);
            int gid = _v.GroupId;
            if (!_groupedDataMap.TryGetValue(gid, out var list))
            {
                list = new System.Collections.Generic.List<GuideStepConfig>();
                _groupedDataMap[gid] = list;
            }
            list.Add(_v);
        }
    }

    #region 静态访问

    private static TbGuideStepConfig m_instance;
    public static TbGuideStepConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbGuideStepConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out GuideStepConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static GuideStepConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, GuideStepConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<GuideStepConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, GuideStepConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<GuideStepConfig> dataList => _dataList;

    public GuideStepConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GuideStepConfig Get(int key) => _dataMap[key];
    public GuideStepConfig this[int key] => _dataMap[key];

    #region GroupId 生成按组分配的字典数据

    public System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<GuideStepConfig>> _groupedDataMap;
    public static System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<GuideStepConfig>> GroupedDataMap => Instance._groupedDataMap;

    public static System.Collections.Generic.List<GuideStepConfig> GetListByGroupId(int groupID)
        => Instance._groupedDataMap.TryGetValue(groupID, out var list) ? list : null;

    #endregion
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

