
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 新手引导组配置表
/// </summary>
public partial class TbGuideGroupConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GuideGroupConfig> _dataMap;
    private readonly System.Collections.Generic.List<GuideGroupConfig> _dataList;
    
    public TbGuideGroupConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GuideGroupConfig>(n);
        _dataList = new System.Collections.Generic.List<GuideGroupConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GuideGroupConfig _v;
            _v = global::GameProto.GuideGroupConfig.DeserializeGuideGroupConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GroupId, _v);
        }
    }

    #region 静态访问

    private static TbGuideGroupConfig m_instance;
    public static TbGuideGroupConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbGuideGroupConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out GuideGroupConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static GuideGroupConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, GuideGroupConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<GuideGroupConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, GuideGroupConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<GuideGroupConfig> dataList => _dataList;

    public GuideGroupConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GuideGroupConfig Get(int key) => _dataMap[key];
    public GuideGroupConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

