
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 模型配置表
/// </summary>
public partial class TbModelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ModelConfig> _dataMap;
    private readonly System.Collections.Generic.List<ModelConfig> _dataList;
    
    public TbModelConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ModelConfig>(n);
        _dataList = new System.Collections.Generic.List<ModelConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ModelConfig _v;
            _v = global::GameProto.ModelConfig.DeserializeModelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ModelID, _v);
        }
    }

    #region 静态访问

    private static TbModelConfig m_instance;
    public static TbModelConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbModelConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out ModelConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static ModelConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, ModelConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<ModelConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, ModelConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<ModelConfig> dataList => _dataList;

    public ModelConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ModelConfig Get(int key) => _dataMap[key];
    public ModelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

