
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 怪物配置表
/// </summary>
public partial class TbMonsterConfig
{
    private readonly System.Collections.Generic.Dictionary<int, MonsterConfig> _dataMap;
    private readonly System.Collections.Generic.List<MonsterConfig> _dataList;
    
    public TbMonsterConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, MonsterConfig>(n);
        _dataList = new System.Collections.Generic.List<MonsterConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            MonsterConfig _v;
            _v = global::GameProto.MonsterConfig.DeserializeMonsterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.MonsterID, _v);
        }
    }

    #region 静态访问

    private static TbMonsterConfig m_instance;
    public static TbMonsterConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbMonsterConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out MonsterConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static MonsterConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, MonsterConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<MonsterConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, MonsterConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<MonsterConfig> dataList => _dataList;

    public MonsterConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MonsterConfig Get(int key) => _dataMap[key];
    public MonsterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

