
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 音效配置表
/// </summary>
public partial class TbSoundConfig
{
    private readonly System.Collections.Generic.Dictionary<int, SoundConfig> _dataMap;
    private readonly System.Collections.Generic.List<SoundConfig> _dataList;
    
    public TbSoundConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, SoundConfig>(n);
        _dataList = new System.Collections.Generic.List<SoundConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            SoundConfig _v;
            _v = global::GameProto.SoundConfig.DeserializeSoundConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    #region 静态访问

    private static TbSoundConfig m_instance;
    public static TbSoundConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbSoundConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out SoundConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static SoundConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, SoundConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<SoundConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, SoundConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<SoundConfig> dataList => _dataList;

    public SoundConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SoundConfig Get(int key) => _dataMap[key];
    public SoundConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

