
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public partial struct vector2int
{
    
    public vector2int(ByteBuf _buf) 
    {
        X = _buf.ReadInt();
        Y = _buf.ReadInt();
    }

    public static vector2int Deserializevector2int(ByteBuf _buf)
    {
        return new vector2int(_buf);
    }

    public int X;
    public int Y;


    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref vector2int other)
    {
        other.X = X;
        other.Y = Y;
    }
    
    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "}";
    }
}
}

