
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public partial struct vector4
{
    
    public vector4(ByteBuf _buf) 
    {
        X = _buf.ReadFloat();
        Y = _buf.ReadFloat();
        Z = _buf.ReadFloat();
        W = _buf.ReadFloat();
    }

    public static vector4 Deserializevector4(ByteBuf _buf)
    {
        return new vector4(_buf);
    }

    public float X;
    public float Y;
    public float Z;
    public float W;


    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref vector4 other)
    {
        other.X = X;
        other.Y = Y;
        other.Z = Z;
        other.W = W;
    }
    
    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "z:" + Z + ","
        + "w:" + W + ","
        + "}";
    }
}
}

