
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public partial struct vector3int
{
    
    public vector3int(ByteBuf _buf) 
    {
        X = _buf.ReadInt();
        Y = _buf.ReadInt();
        Z = _buf.ReadInt();
    }

    public static vector3int Deserializevector3int(ByteBuf _buf)
    {
        return new vector3int(_buf);
    }

    public int X;
    public int Y;
    public int Z;


    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref vector3int other)
    {
        other.X = X;
        other.Y = Y;
        other.Z = Z;
    }
    
    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "z:" + Z + ","
        + "}";
    }
}
}

