
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class WeaponModelBaseParam : Luban.BeanBase
{
    public WeaponModelBaseParam() { }
    
    public WeaponModelBaseParam(ByteBuf _buf) 
    {
        OffsetX = _buf.ReadFloat();
        OffsetY = _buf.ReadFloat();
        RotationX = _buf.ReadFloat();
        RotationY = _buf.ReadFloat();
        RotationZ = _buf.ReadFloat();
        Scale = _buf.ReadFloat();
    }

    public static WeaponModelBaseParam DeserializeWeaponModelBaseParam(ByteBuf _buf)
    {
        return new WeaponModelBaseParam(_buf);
    }

    /// <summary>
    /// 偏移X
    /// </summary>
    public float OffsetX;
    /// <summary>
    /// 偏移Y
    /// </summary>
    public float OffsetY;
    /// <summary>
    /// 旋转X
    /// </summary>
    public float RotationX;
    /// <summary>
    /// 旋转Y
    /// </summary>
    public float RotationY;
    /// <summary>
    /// 旋转Z
    /// </summary>
    public float RotationZ;
    /// <summary>
    /// 缩放
    /// </summary>
    public float Scale;

    public const int __ID__ = 1070153839;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref WeaponModelBaseParam other)
    {
        if (other == null)
        {
            other = new WeaponModelBaseParam();
        }
        other.OffsetX = OffsetX;
        other.OffsetY = OffsetY;
        other.RotationX = RotationX;
        other.RotationY = RotationY;
        other.RotationZ = RotationZ;
        other.Scale = Scale;
    }
    
    public override string ToString()
    {
        return "{ "
        + "OffsetX:" + OffsetX + ","
        + "OffsetY:" + OffsetY + ","
        + "RotationX:" + RotationX + ","
        + "RotationY:" + RotationY + ","
        + "RotationZ:" + RotationZ + ","
        + "Scale:" + Scale + ","
        + "}";
    }
}
}

