
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    /// <summary>
    /// 活动类型枚举
    /// </summary>
    public enum ActivityType
    {
        /// <summary>
        /// 无
        /// </summary>
        ACTIVITY_TYPE_NONE = 0,
    }

} 

