
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class AttrModifuerData : Luban.BeanBase
{
    public AttrModifuerData() { }
    
    public AttrModifuerData(ByteBuf _buf) 
    {
        AttrType = _buf.ReadInt();
        ModifyMode = _buf.ReadByte();
        Value = _buf.ReadFloat();
    }

    public static AttrModifuerData DeserializeAttrModifuerData(ByteBuf _buf)
    {
        return new AttrModifuerData(_buf);
    }

    /// <summary>
    /// 属性类型
    /// </summary>
    public int AttrType;
    /// <summary>
    /// 修正模式
    /// </summary>
    public byte ModifyMode;
    /// <summary>
    /// 修正值
    /// </summary>
    public float Value;

    public const int __ID__ = -329712930;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref AttrModifuerData other)
    {
        if (other == null)
        {
            other = new AttrModifuerData();
        }
        other.AttrType = AttrType;
        other.ModifyMode = ModifyMode;
        other.Value = Value;
    }
    
    public override string ToString()
    {
        return "{ "
        + "AttrType:" + AttrType + ","
        + "ModifyMode:" + ModifyMode + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

