
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    /// <summary>
    /// 货币枚举类型
    /// </summary>
    public enum CurrencyType
    {
        /// <summary>
        /// 无
        /// </summary>
        CURRENCY_NONE = 0,
        /// <summary>
        /// 金币
        /// </summary>
        CURRENCY_GOLD = 1,
        /// <summary>
        /// 钻石
        /// </summary>
        CURRENCY_DIAMOND = 2,
        /// <summary>
        /// 体力
        /// </summary>
        CURRENCY_STAM = 3,
        /// <summary>
        /// 经验
        /// </summary>
        CURRENCY_EXP = 4,
        /// <summary>
        /// 最大
        /// </summary>
        CURRENCY_MAX = 5,
    }

} 

