
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class FuncParamConfig : Luban.BeanBase
{
    public FuncParamConfig() { }
    
    public FuncParamConfig(ByteBuf _buf) 
    {
        AccountTokenPublicKeyPem = _buf.ReadString();
        AccountTokenPrivateKeyPem = _buf.ReadString();
        AccountTokenExpireTime = _buf.ReadInt();
    }

    public static FuncParamConfig DeserializeFuncParamConfig(ByteBuf _buf)
    {
        return new FuncParamConfig(_buf);
    }

    /// <summary>
    /// 账号Token公钥
    /// </summary>
    public string AccountTokenPublicKeyPem;
    /// <summary>
    /// 账号Token私钥
    /// </summary>
    public string AccountTokenPrivateKeyPem;
    /// <summary>
    /// 账号Token过期时间(毫秒)
    /// </summary>
    public int AccountTokenExpireTime;

    public const int __ID__ = -1155611477;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref FuncParamConfig other)
    {
        if (other == null)
        {
            other = new FuncParamConfig();
        }
        other.AccountTokenPublicKeyPem = AccountTokenPublicKeyPem;
        other.AccountTokenPrivateKeyPem = AccountTokenPrivateKeyPem;
        other.AccountTokenExpireTime = AccountTokenExpireTime;
    }
    
    public override string ToString()
    {
        return "{ "
        + "AccountTokenPublicKeyPem:" + AccountTokenPublicKeyPem + ","
        + "AccountTokenPrivateKeyPem:" + AccountTokenPrivateKeyPem + ","
        + "AccountTokenExpireTime:" + AccountTokenExpireTime + ","
        + "}";
    }
}
}

