
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class FuncParamConfig : Luban.BeanBase
{
    public FuncParamConfig() { }
    
    public FuncParamConfig(ByteBuf _buf) 
    {
        AccountTokenPublicKeyPem = _buf.ReadString();
        AccountTokenPrivateKeyPem = _buf.ReadString();
        AccountTokenExpireTime = _buf.ReadInt();
        AccountValidIssuer = _buf.ReadString();
        AccountValidAudience = _buf.ReadString();
        AccountRegisterSessionLifeTime = _buf.ReadInt();
        RecentServerMaxCount = _buf.ReadInt();
        OldSessionLifeTime = _buf.ReadInt();
        DelayOfflineTime = _buf.ReadInt();
    }

    public static FuncParamConfig DeserializeFuncParamConfig(ByteBuf _buf)
    {
        return new FuncParamConfig(_buf);
    }

    /// <summary>
    /// 账号Token公钥
    /// </summary>
    public string AccountTokenPublicKeyPem;
    /// <summary>
    /// 账号Token私钥
    /// </summary>
    public string AccountTokenPrivateKeyPem;
    /// <summary>
    /// 账号Token过期时间(毫秒)
    /// </summary>
    public int AccountTokenExpireTime;
    /// <summary>
    /// 发证者
    /// </summary>
    public string AccountValidIssuer;
    /// <summary>
    /// 受众
    /// </summary>
    public string AccountValidAudience;
    /// <summary>
    /// 注册Session的延迟销毁时间(毫秒)(短链接)
    /// </summary>
    public int AccountRegisterSessionLifeTime;
    /// <summary>
    /// 记录服务器最近登录最大个数
    /// </summary>
    public int RecentServerMaxCount;
    /// <summary>
    /// 断线重连时旧的Session生命周期(毫秒)
    /// </summary>
    public int OldSessionLifeTime;
    /// <summary>
    /// 延迟下线时间(毫秒)
    /// </summary>
    public int DelayOfflineTime;

    public const int __ID__ = -1155611477;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref FuncParamConfig other)
    {
        if (other == null)
        {
            other = new FuncParamConfig();
        }
        other.AccountTokenPublicKeyPem = AccountTokenPublicKeyPem;
        other.AccountTokenPrivateKeyPem = AccountTokenPrivateKeyPem;
        other.AccountTokenExpireTime = AccountTokenExpireTime;
        other.AccountValidIssuer = AccountValidIssuer;
        other.AccountValidAudience = AccountValidAudience;
        other.AccountRegisterSessionLifeTime = AccountRegisterSessionLifeTime;
        other.RecentServerMaxCount = RecentServerMaxCount;
        other.OldSessionLifeTime = OldSessionLifeTime;
        other.DelayOfflineTime = DelayOfflineTime;
    }
    
    public override string ToString()
    {
        return "{ "
        + "AccountTokenPublicKeyPem:" + AccountTokenPublicKeyPem + ","
        + "AccountTokenPrivateKeyPem:" + AccountTokenPrivateKeyPem + ","
        + "AccountTokenExpireTime:" + AccountTokenExpireTime + ","
        + "AccountValidIssuer:" + AccountValidIssuer + ","
        + "AccountValidAudience:" + AccountValidAudience + ","
        + "AccountRegisterSessionLifeTime:" + AccountRegisterSessionLifeTime + ","
        + "RecentServerMaxCount:" + RecentServerMaxCount + ","
        + "OldSessionLifeTime:" + OldSessionLifeTime + ","
        + "DelayOfflineTime:" + DelayOfflineTime + ","
        + "}";
    }
}
}

