
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    /// <summary>
    /// 系统开放类型
    /// </summary>
    public enum FuncType
    {
        /// <summary>
        /// 异常
        /// </summary>
        FUNC_TYPE_NONE = 0,
        /// <summary>
        /// 商城
        /// </summary>
        FUNC_TYPE_SHOP = 1,
        /// <summary>
        /// 角色
        /// </summary>
        FUNC_TYPE_ACTOR = 2,
        /// <summary>
        /// 主界面
        /// </summary>
        FUNC_TYPE_MAIN = 3,
        /// <summary>
        /// 公会
        /// </summary>
        FUNC_TYPE_LEAGUE = 4,
        /// <summary>
        /// 玩法
        /// </summary>
        FUNC_TYPE_GAMEPLAY = 5,
        /// <summary>
        /// 家园
        /// </summary>
        FUNC_TYPE_HOME = 6,
    }

} 

