
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class ModelConfig : Luban.BeanBase
{
    public ModelConfig() { }
    
    public ModelConfig(ByteBuf _buf) 
    {
        ModelID = _buf.ReadInt();
        UISpineLocation = _buf.ReadString();
        ModelLocation = _buf.ReadString();
        FrameCfgLocation = _buf.ReadString();
        DeathFrameSpeed = _buf.ReadFloat();
        ModelScale = _buf.ReadFloat();
        UIScale = _buf.ReadFloat();
        ShowType = _buf.ReadByte();
        ShowShadow = _buf.ReadByte();
        ShadowWidth = _buf.ReadFloat();
        ShadowHeight = _buf.ReadFloat();
        ShadowScaleX = _buf.ReadFloat();
        ShadowScaleY = _buf.ReadFloat();
        ShadowOffsetX = _buf.ReadFloat();
        ShadowOffsetY = _buf.ReadFloat();
        BaseMoveSpeed = _buf.ReadFloat();
        EnableCollision = _buf.ReadBool();
        UseAabbCollision = _buf.ReadBool();
        CollisionRadius = _buf.ReadFloat();
        CollisionHeight = _buf.ReadFloat();
        HpBarOffsetX = _buf.ReadFloat();
        HpBarOffsetY = _buf.ReadFloat();
        HitFlashColorR = _buf.ReadFloat();
        HitFlashColorG = _buf.ReadFloat();
        HitFlashColorB = _buf.ReadFloat();
        HitFullFlashTime = _buf.ReadFloat();
        HitFlashTime = _buf.ReadFloat();
        DeathFadeOutDurTime = _buf.ReadFloat();
        DeathEffectSoundID = _buf.ReadInt();
    }

    public static ModelConfig DeserializeModelConfig(ByteBuf _buf)
    {
        return new ModelConfig(_buf);
    }

    /// <summary>
    /// 模型ID
    /// </summary>
    public int ModelID;
    /// <summary>
    /// UISpine可寻址地址
    /// </summary>
    public string UISpineLocation;
    /// <summary>
    /// Model可寻址地址
    /// </summary>
    public string ModelLocation;
    /// <summary>
    /// 帧动画配置文件
    /// </summary>
    public string FrameCfgLocation;
    /// <summary>
    /// 死亡动画速度
    /// </summary>
    public float DeathFrameSpeed;
    /// <summary>
    /// 模型缩放
    /// </summary>
    public float ModelScale;
    /// <summary>
    /// UI模型缩放
    /// </summary>
    public float UIScale;
    /// <summary>
    /// 显示类型
    /// </summary>
    public byte ShowType;
    /// <summary>
    /// 显示阴影
    /// </summary>
    public byte ShowShadow;
    /// <summary>
    /// 阴影宽度
    /// </summary>
    public float ShadowWidth;
    /// <summary>
    /// 阴影高度
    /// </summary>
    public float ShadowHeight;
    /// <summary>
    /// 阴影缩放X
    /// </summary>
    public float ShadowScaleX;
    /// <summary>
    /// 阴影缩放Y
    /// </summary>
    public float ShadowScaleY;
    /// <summary>
    /// 阴影偏移X
    /// </summary>
    public float ShadowOffsetX;
    /// <summary>
    /// 阴影偏移Y
    /// </summary>
    public float ShadowOffsetY;
    /// <summary>
    /// 参考移动速度
    /// </summary>
    public float BaseMoveSpeed;
    /// <summary>
    /// 是否开启碰撞
    /// </summary>
    public bool EnableCollision;
    /// <summary>
    /// 是否矩形碰撞
    /// </summary>
    public bool UseAabbCollision;
    /// <summary>
    /// 碰撞半径
    /// </summary>
    public float CollisionRadius;
    /// <summary>
    /// 碰撞高度
    /// </summary>
    public float CollisionHeight;
    /// <summary>
    /// 血条高度偏移X
    /// </summary>
    public float HpBarOffsetX;
    /// <summary>
    /// 血条高度偏移Y
    /// </summary>
    public float HpBarOffsetY;
    /// <summary>
    /// 受击高亮R
    /// </summary>
    public float HitFlashColorR;
    /// <summary>
    /// 受击高亮G
    /// </summary>
    public float HitFlashColorG;
    /// <summary>
    /// 受击高亮B
    /// </summary>
    public float HitFlashColorB;
    /// <summary>
    /// 受击高亮总持续时间
    /// </summary>
    public float HitFullFlashTime;
    /// <summary>
    /// 受击高亮持续时间
    /// </summary>
    public float HitFlashTime;
    /// <summary>
    /// 死亡渐变消失时间
    /// </summary>
    public float DeathFadeOutDurTime;
    /// <summary>
    /// 死亡音效ID
    /// </summary>
    public int DeathEffectSoundID;

    public const int __ID__ = 1694060459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref ModelConfig other)
    {
        if (other == null)
        {
            other = new ModelConfig();
        }
        other.ModelID = ModelID;
        other.UISpineLocation = UISpineLocation;
        other.ModelLocation = ModelLocation;
        other.FrameCfgLocation = FrameCfgLocation;
        other.DeathFrameSpeed = DeathFrameSpeed;
        other.ModelScale = ModelScale;
        other.UIScale = UIScale;
        other.ShowType = ShowType;
        other.ShowShadow = ShowShadow;
        other.ShadowWidth = ShadowWidth;
        other.ShadowHeight = ShadowHeight;
        other.ShadowScaleX = ShadowScaleX;
        other.ShadowScaleY = ShadowScaleY;
        other.ShadowOffsetX = ShadowOffsetX;
        other.ShadowOffsetY = ShadowOffsetY;
        other.BaseMoveSpeed = BaseMoveSpeed;
        other.EnableCollision = EnableCollision;
        other.UseAabbCollision = UseAabbCollision;
        other.CollisionRadius = CollisionRadius;
        other.CollisionHeight = CollisionHeight;
        other.HpBarOffsetX = HpBarOffsetX;
        other.HpBarOffsetY = HpBarOffsetY;
        other.HitFlashColorR = HitFlashColorR;
        other.HitFlashColorG = HitFlashColorG;
        other.HitFlashColorB = HitFlashColorB;
        other.HitFullFlashTime = HitFullFlashTime;
        other.HitFlashTime = HitFlashTime;
        other.DeathFadeOutDurTime = DeathFadeOutDurTime;
        other.DeathEffectSoundID = DeathEffectSoundID;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ModelID:" + ModelID + ","
        + "UISpineLocation:" + UISpineLocation + ","
        + "ModelLocation:" + ModelLocation + ","
        + "FrameCfgLocation:" + FrameCfgLocation + ","
        + "DeathFrameSpeed:" + DeathFrameSpeed + ","
        + "ModelScale:" + ModelScale + ","
        + "UIScale:" + UIScale + ","
        + "ShowType:" + ShowType + ","
        + "ShowShadow:" + ShowShadow + ","
        + "ShadowWidth:" + ShadowWidth + ","
        + "ShadowHeight:" + ShadowHeight + ","
        + "ShadowScaleX:" + ShadowScaleX + ","
        + "ShadowScaleY:" + ShadowScaleY + ","
        + "ShadowOffsetX:" + ShadowOffsetX + ","
        + "ShadowOffsetY:" + ShadowOffsetY + ","
        + "BaseMoveSpeed:" + BaseMoveSpeed + ","
        + "EnableCollision:" + EnableCollision + ","
        + "UseAabbCollision:" + UseAabbCollision + ","
        + "CollisionRadius:" + CollisionRadius + ","
        + "CollisionHeight:" + CollisionHeight + ","
        + "HpBarOffsetX:" + HpBarOffsetX + ","
        + "HpBarOffsetY:" + HpBarOffsetY + ","
        + "HitFlashColorR:" + HitFlashColorR + ","
        + "HitFlashColorG:" + HitFlashColorG + ","
        + "HitFlashColorB:" + HitFlashColorB + ","
        + "HitFullFlashTime:" + HitFullFlashTime + ","
        + "HitFlashTime:" + HitFlashTime + ","
        + "DeathFadeOutDurTime:" + DeathFadeOutDurTime + ","
        + "DeathEffectSoundID:" + DeathEffectSoundID + ","
        + "}";
    }
}
}

