
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto
{ 
    /// <summary>
    /// 怪物类型
    /// </summary>
    public enum MonsterType
    {
        /// <summary>
        /// 普通怪物
        /// </summary>
        Normal = 1,
        /// <summary>
        /// 精英
        /// </summary>
        Elite = 2,
        /// <summary>
        /// Boss
        /// </summary>
        Boss = 3,
    }

} 

