
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 章节通关货币奖励类型
/// </summary>
public sealed partial class PassChapterCurrency : Luban.BeanBase
{
    public PassChapterCurrency() { }
    
    public PassChapterCurrency(ByteBuf _buf) 
    {
        CurrencyType = _buf.ReadInt();
        BaseNum = _buf.ReadInt();
        ExtraNum = _buf.ReadInt();
    }

    public static PassChapterCurrency DeserializePassChapterCurrency(ByteBuf _buf)
    {
        return new PassChapterCurrency(_buf);
    }

    /// <summary>
    /// 货币类型
    /// </summary>
    public int CurrencyType;
    /// <summary>
    /// 基础值
    /// </summary>
    public int BaseNum;
    /// <summary>
    /// 加成值
    /// </summary>
    public int ExtraNum;

    public const int __ID__ = 1517914893;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref PassChapterCurrency other)
    {
        if (other == null)
        {
            other = new PassChapterCurrency();
        }
        other.CurrencyType = CurrencyType;
        other.BaseNum = BaseNum;
        other.ExtraNum = ExtraNum;
    }
    
    public override string ToString()
    {
        return "{ "
        + "CurrencyType:" + CurrencyType + ","
        + "BaseNum:" + BaseNum + ","
        + "ExtraNum:" + ExtraNum + ","
        + "}";
    }
}
}

