
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameProto
{
    public partial class Tables
    {
        #region The Tables

        private System.Func<string, ByteBuf> m_defaultLoader;

        /// <summary>
        /// 文本配置表
        /// </summary>
        private TbTextConfig m_TbTextConfig;
        public TbTextConfig TbTextConfig 
        {
            get
            {
                if (m_TbTextConfig == null)
                {
                    m_TbTextConfig = new TbTextConfig(m_defaultLoader("tbtextconfig"));
                    m_TbTextConfig.ResolveRef(this);
                }
                return m_TbTextConfig;
            }
            set
            {
                m_TbTextConfig = value;
                m_TbTextConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 道具配置表
        /// </summary>
        private TbItemConfig m_TbItemConfig;
        public TbItemConfig TbItemConfig 
        {
            get
            {
                if (m_TbItemConfig == null)
                {
                    m_TbItemConfig = new TbItemConfig(m_defaultLoader("tbitemconfig"));
                    m_TbItemConfig.ResolveRef(this);
                }
                return m_TbItemConfig;
            }
            set
            {
                m_TbItemConfig = value;
                m_TbItemConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 货币配置表
        /// </summary>
        private TbCurrencyConfig m_TbCurrencyConfig;
        public TbCurrencyConfig TbCurrencyConfig 
        {
            get
            {
                if (m_TbCurrencyConfig == null)
                {
                    m_TbCurrencyConfig = new TbCurrencyConfig(m_defaultLoader("tbcurrencyconfig"));
                    m_TbCurrencyConfig.ResolveRef(this);
                }
                return m_TbCurrencyConfig;
            }
            set
            {
                m_TbCurrencyConfig = value;
                m_TbCurrencyConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 获取途径配置表
        /// </summary>
        private TbGetWayConfig m_TbGetWayConfig;
        public TbGetWayConfig TbGetWayConfig 
        {
            get
            {
                if (m_TbGetWayConfig == null)
                {
                    m_TbGetWayConfig = new TbGetWayConfig(m_defaultLoader("tbgetwayconfig"));
                    m_TbGetWayConfig.ResolveRef(this);
                }
                return m_TbGetWayConfig;
            }
            set
            {
                m_TbGetWayConfig = value;
                m_TbGetWayConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 音效配置表
        /// </summary>
        private TbSoundConfig m_TbSoundConfig;
        public TbSoundConfig TbSoundConfig 
        {
            get
            {
                if (m_TbSoundConfig == null)
                {
                    m_TbSoundConfig = new TbSoundConfig(m_defaultLoader("tbsoundconfig"));
                    m_TbSoundConfig.ResolveRef(this);
                }
                return m_TbSoundConfig;
            }
            set
            {
                m_TbSoundConfig = value;
                m_TbSoundConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 模型配置表
        /// </summary>
        private TbModelConfig m_TbModelConfig;
        public TbModelConfig TbModelConfig 
        {
            get
            {
                if (m_TbModelConfig == null)
                {
                    m_TbModelConfig = new TbModelConfig(m_defaultLoader("tbmodelconfig"));
                    m_TbModelConfig.ResolveRef(this);
                }
                return m_TbModelConfig;
            }
            set
            {
                m_TbModelConfig = value;
                m_TbModelConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 武器模型配置表
        /// </summary>
        private TbWeaponModelConfig m_TbWeaponModelConfig;
        public TbWeaponModelConfig TbWeaponModelConfig 
        {
            get
            {
                if (m_TbWeaponModelConfig == null)
                {
                    m_TbWeaponModelConfig = new TbWeaponModelConfig(m_defaultLoader("tbweaponmodelconfig"));
                    m_TbWeaponModelConfig.ResolveRef(this);
                }
                return m_TbWeaponModelConfig;
            }
            set
            {
                m_TbWeaponModelConfig = value;
                m_TbWeaponModelConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 特效配置表
        /// </summary>
        private TbEffectConfig m_TbEffectConfig;
        public TbEffectConfig TbEffectConfig 
        {
            get
            {
                if (m_TbEffectConfig == null)
                {
                    m_TbEffectConfig = new TbEffectConfig(m_defaultLoader("tbeffectconfig"));
                    m_TbEffectConfig.ResolveRef(this);
                }
                return m_TbEffectConfig;
            }
            set
            {
                m_TbEffectConfig = value;
                m_TbEffectConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// GM配置表
        /// </summary>
        private TbGmConfig m_TbGmConfig;
        public TbGmConfig TbGmConfig 
        {
            get
            {
                if (m_TbGmConfig == null)
                {
                    m_TbGmConfig = new TbGmConfig(m_defaultLoader("tbgmconfig"));
                    m_TbGmConfig.ResolveRef(this);
                }
                return m_TbGmConfig;
            }
            set
            {
                m_TbGmConfig = value;
                m_TbGmConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 系统开放配置表
        /// </summary>
        private TbFuncOpenConfig m_TbFuncOpenConfig;
        public TbFuncOpenConfig TbFuncOpenConfig 
        {
            get
            {
                if (m_TbFuncOpenConfig == null)
                {
                    m_TbFuncOpenConfig = new TbFuncOpenConfig(m_defaultLoader("tbfuncopenconfig"));
                    m_TbFuncOpenConfig.ResolveRef(this);
                }
                return m_TbFuncOpenConfig;
            }
            set
            {
                m_TbFuncOpenConfig = value;
                m_TbFuncOpenConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 功能参数配置表
        /// </summary>
        private TbFuncParamConfig m_TbFuncParamConfig;
        public TbFuncParamConfig TbFuncParamConfig 
        {
            get
            {
                if (m_TbFuncParamConfig == null)
                {
                    m_TbFuncParamConfig = new TbFuncParamConfig(m_defaultLoader("tbfuncparamconfig"));
                    m_TbFuncParamConfig.ResolveRef(this);
                }
                return m_TbFuncParamConfig;
            }
            set
            {
                m_TbFuncParamConfig = value;
                m_TbFuncParamConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 章节配置表
        /// </summary>
        private TbChapterConfig m_TbChapterConfig;
        public TbChapterConfig TbChapterConfig 
        {
            get
            {
                if (m_TbChapterConfig == null)
                {
                    m_TbChapterConfig = new TbChapterConfig(m_defaultLoader("tbchapterconfig"));
                    m_TbChapterConfig.ResolveRef(this);
                }
                return m_TbChapterConfig;
            }
            set
            {
                m_TbChapterConfig = value;
                m_TbChapterConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 服务器配置表
        /// </summary>
        private TbServerConfig m_TbServerConfig;
        public TbServerConfig TbServerConfig 
        {
            get
            {
                if (m_TbServerConfig == null)
                {
                    m_TbServerConfig = new TbServerConfig(m_defaultLoader("tbserverconfig"));
                    m_TbServerConfig.ResolveRef(this);
                }
                return m_TbServerConfig;
            }
            set
            {
                m_TbServerConfig = value;
                m_TbServerConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 服务器状态配置表
        /// </summary>
        private TbServerStateConfig m_TbServerStateConfig;
        public TbServerStateConfig TbServerStateConfig 
        {
            get
            {
                if (m_TbServerStateConfig == null)
                {
                    m_TbServerStateConfig = new TbServerStateConfig(m_defaultLoader("tbserverstateconfig"));
                    m_TbServerStateConfig.ResolveRef(this);
                }
                return m_TbServerStateConfig;
            }
            set
            {
                m_TbServerStateConfig = value;
                m_TbServerStateConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 活动开启配置表
        /// </summary>
        private TbActivityOpenConfig m_TbActivityOpenConfig;
        public TbActivityOpenConfig TbActivityOpenConfig 
        {
            get
            {
                if (m_TbActivityOpenConfig == null)
                {
                    m_TbActivityOpenConfig = new TbActivityOpenConfig(m_defaultLoader("tbactivityopenconfig"));
                    m_TbActivityOpenConfig.ResolveRef(this);
                }
                return m_TbActivityOpenConfig;
            }
            set
            {
                m_TbActivityOpenConfig = value;
                m_TbActivityOpenConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 角色初始配置表
        /// </summary>
        private TbPlayerInitConfig m_TbPlayerInitConfig;
        public TbPlayerInitConfig TbPlayerInitConfig 
        {
            get
            {
                if (m_TbPlayerInitConfig == null)
                {
                    m_TbPlayerInitConfig = new TbPlayerInitConfig(m_defaultLoader("tbplayerinitconfig"));
                    m_TbPlayerInitConfig.ResolveRef(this);
                }
                return m_TbPlayerInitConfig;
            }
            set
            {
                m_TbPlayerInitConfig = value;
                m_TbPlayerInitConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 随机名配置表
        /// </summary>
        private TbRandomNameConfig m_TbRandomNameConfig;
        public TbRandomNameConfig TbRandomNameConfig 
        {
            get
            {
                if (m_TbRandomNameConfig == null)
                {
                    m_TbRandomNameConfig = new TbRandomNameConfig(m_defaultLoader("tbrandomnameconfig"));
                    m_TbRandomNameConfig.ResolveRef(this);
                }
                return m_TbRandomNameConfig;
            }
            set
            {
                m_TbRandomNameConfig = value;
                m_TbRandomNameConfig.ResolveRef(this);
            }
        }

        #endregion

        public Tables(System.Func<string, ByteBuf> loader)
        {
            SetDefaultLoader(loader);
            Init();
        }

        public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
        {
            m_defaultLoader = null;
            m_defaultLoader = loader;
        }

        public void Reload()
        {
            m_TbTextConfig = null;
            m_TbItemConfig = null;
            m_TbCurrencyConfig = null;
            m_TbGetWayConfig = null;
            m_TbSoundConfig = null;
            m_TbModelConfig = null;
            m_TbWeaponModelConfig = null;
            m_TbEffectConfig = null;
            m_TbGmConfig = null;
            m_TbFuncOpenConfig = null;
            m_TbFuncParamConfig = null;
            m_TbChapterConfig = null;
            m_TbServerConfig = null;
            m_TbServerStateConfig = null;
            m_TbActivityOpenConfig = null;
            m_TbPlayerInitConfig = null;
            m_TbRandomNameConfig = null;
        }

        public void Init(){}
    }
}
