
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 获取途径配置表
/// </summary>
public partial class TbGetWayConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GetWayConfig> _dataMap;
    private readonly System.Collections.Generic.List<GetWayConfig> _dataList;
    
    public TbGetWayConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GetWayConfig>(n);
        _dataList = new System.Collections.Generic.List<GetWayConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GetWayConfig _v;
            _v = global::GameProto.GetWayConfig.DeserializeGetWayConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.WayID, _v);
        }
    }

    #region 静态访问

    private static TbGetWayConfig m_instance;
    public static TbGetWayConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbGetWayConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out GetWayConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static GetWayConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, GetWayConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<GetWayConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, GetWayConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<GetWayConfig> dataList => _dataList;

    public GetWayConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GetWayConfig Get(int key) => _dataMap[key];
    public GetWayConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

