
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 地图配置表
/// </summary>
public partial class TbMapConfig
{
    private readonly System.Collections.Generic.Dictionary<int, MapConfig> _dataMap;
    private readonly System.Collections.Generic.List<MapConfig> _dataList;
    
    public TbMapConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, MapConfig>(n);
        _dataList = new System.Collections.Generic.List<MapConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            MapConfig _v;
            _v = global::GameProto.MapConfig.DeserializeMapConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.MapID, _v);
        }
    }

    #region 静态访问

    private static TbMapConfig m_instance;
    public static TbMapConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbMapConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out MapConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static MapConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, MapConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<MapConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, MapConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<MapConfig> dataList => _dataList;

    public MapConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MapConfig Get(int key) => _dataMap[key];
    public MapConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

