
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 路径点配置表
/// </summary>
public partial class TbPathConfig
{
    private readonly System.Collections.Generic.Dictionary<int, PathConfig> _dataMap;
    private readonly System.Collections.Generic.List<PathConfig> _dataList;
    
    public TbPathConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, PathConfig>(n);
        _dataList = new System.Collections.Generic.List<PathConfig>(n);
        _groupedDataMap = new System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<PathConfig>>();
        for(int i = n ; i > 0 ; --i)
        {
            PathConfig _v;
            _v = global::GameProto.PathConfig.DeserializePathConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
            int gid = _v.GroupID;
            if (!_groupedDataMap.TryGetValue(gid, out var list))
            {
                list = new System.Collections.Generic.List<PathConfig>();
                _groupedDataMap[gid] = list;
            }
            list.Add(_v);
        }
    }

    #region 静态访问

    private static TbPathConfig m_instance;
    public static TbPathConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbPathConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out PathConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static PathConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, PathConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<PathConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, PathConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<PathConfig> dataList => _dataList;

    public PathConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PathConfig Get(int key) => _dataMap[key];
    public PathConfig this[int key] => _dataMap[key];

    #region GroupId 生成按组分配的字典数据

    public System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<PathConfig>> _groupedDataMap;
    public static System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<PathConfig>> GroupedDataMap => Instance._groupedDataMap;

    public static System.Collections.Generic.List<PathConfig> GetListByGroupID(int groupID)
        => Instance._groupedDataMap.TryGetValue(groupID, out var list) ? list : null;

    #endregion
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

