
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 角色模型配对表
/// </summary>
public partial class TbPlayerModelPairConfig
{
    private readonly System.Collections.Generic.List<PlayerModelPairConfig> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), PlayerModelPairConfig> _dataMapUnion;

    public TbPlayerModelPairConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<PlayerModelPairConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            PlayerModelPairConfig _v;
            _v = global::GameProto.PlayerModelPairConfig.DeserializePlayerModelPairConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), PlayerModelPairConfig>(n);
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.RoleBodyType, _v.ClothID), _v);
        }
    }

    #region 静态访问

    private static TbPlayerModelPairConfig m_instance;
    public static TbPlayerModelPairConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbPlayerModelPairConfig : m_instance;
    public static System.Collections.Generic.List<PlayerModelPairConfig> DataList => Instance._dataList;

    public static PlayerModelPairConfig Get(int RoleBodyType, int ClothID) => Instance._dataMapUnion.TryGetValue((RoleBodyType, ClothID), out PlayerModelPairConfig __v) ? __v : default;

    #endregion

    public System.Collections.Generic.List<PlayerModelPairConfig> dataList => _dataList;

    public PlayerModelPairConfig GetNoStatic(int RoleBodyType, int ClothID) => _dataMapUnion.TryGetValue((RoleBodyType, ClothID), out PlayerModelPairConfig __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

