
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 角色初始配置表
/// </summary>
public partial class TbPlayerInitConfig
{
    private readonly System.Collections.Generic.Dictionary<int, PlayerInitConfig> _dataMap;
    private readonly System.Collections.Generic.List<PlayerInitConfig> _dataList;
    
    public TbPlayerInitConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, PlayerInitConfig>(n);
        _dataList = new System.Collections.Generic.List<PlayerInitConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            PlayerInitConfig _v;
            _v = global::GameProto.PlayerInitConfig.DeserializePlayerInitConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    #region 静态访问

    private static TbPlayerInitConfig m_instance;
    public static TbPlayerInitConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbPlayerInitConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out PlayerInitConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static PlayerInitConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, PlayerInitConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<PlayerInitConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, PlayerInitConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<PlayerInitConfig> dataList => _dataList;

    public PlayerInitConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PlayerInitConfig Get(int key) => _dataMap[key];
    public PlayerInitConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

