
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 随机名配置表
/// </summary>
public partial class TbRandomNameConfig
{
    private readonly System.Collections.Generic.Dictionary<int, RandomNameConfig> _dataMap;
    private readonly System.Collections.Generic.List<RandomNameConfig> _dataList;
    
    public TbRandomNameConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, RandomNameConfig>(n);
        _dataList = new System.Collections.Generic.List<RandomNameConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            RandomNameConfig _v;
            _v = global::GameProto.RandomNameConfig.DeserializeRandomNameConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    #region 静态访问

    private static TbRandomNameConfig m_instance;
    public static TbRandomNameConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbRandomNameConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out RandomNameConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static RandomNameConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, RandomNameConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<RandomNameConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, RandomNameConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<RandomNameConfig> dataList => _dataList;

    public RandomNameConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RandomNameConfig Get(int key) => _dataMap[key];
    public RandomNameConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

