
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 服务器状态配置表
/// </summary>
public partial class TbServerStateConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ServerStateConfig> _dataMap;
    private readonly System.Collections.Generic.List<ServerStateConfig> _dataList;
    
    public TbServerStateConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ServerStateConfig>(n);
        _dataList = new System.Collections.Generic.List<ServerStateConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ServerStateConfig _v;
            _v = global::GameProto.ServerStateConfig.DeserializeServerStateConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    #region 静态访问

    private static TbServerStateConfig m_instance;
    public static TbServerStateConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbServerStateConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out ServerStateConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static ServerStateConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, ServerStateConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<ServerStateConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, ServerStateConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<ServerStateConfig> dataList => _dataList;

    public ServerStateConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ServerStateConfig Get(int key) => _dataMap[key];
    public ServerStateConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

