
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 服务器配置表
/// </summary>
public partial class TbServerConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ServerConfig> _dataMap;
    private readonly System.Collections.Generic.List<ServerConfig> _dataList;
    
    public TbServerConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ServerConfig>(n);
        _dataList = new System.Collections.Generic.List<ServerConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ServerConfig _v;
            _v = global::GameProto.ServerConfig.DeserializeServerConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    #region 静态访问

    private static TbServerConfig m_instance;
    public static TbServerConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbServerConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out ServerConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static ServerConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, ServerConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<ServerConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, ServerConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<ServerConfig> dataList => _dataList;

    public ServerConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ServerConfig Get(int key) => _dataMap[key];
    public ServerConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

