
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 武器模型配置表
/// </summary>
public partial class TbWeaponModelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponModelConfig> _dataMap;
    private readonly System.Collections.Generic.List<WeaponModelConfig> _dataList;
    
    public TbWeaponModelConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponModelConfig>(n);
        _dataList = new System.Collections.Generic.List<WeaponModelConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            WeaponModelConfig _v;
            _v = global::GameProto.WeaponModelConfig.DeserializeWeaponModelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ModelID, _v);
        }
    }

    #region 静态访问

    private static TbWeaponModelConfig m_instance;
    public static TbWeaponModelConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbWeaponModelConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out WeaponModelConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static WeaponModelConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, WeaponModelConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<WeaponModelConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, WeaponModelConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<WeaponModelConfig> dataList => _dataList;

    public WeaponModelConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public WeaponModelConfig Get(int key) => _dataMap[key];
    public WeaponModelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

