using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FrameSpritePoolGenerator.Generator;

[Generator]
public class FrameSpritePoolGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // 初始化
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // 获取当前语法树
        var syntaxTrees = context.Compilation.SyntaxTrees;
        GenerateFrameSpritePoolExecute(context, syntaxTrees);
    }

    #region GenerateGameEvent

    private void GenerateFrameSpritePoolExecute(GeneratorExecutionContext context, IEnumerable<SyntaxTree> syntaxTrees)
    {
        List<string> classNameList = new List<string>();

        foreach (var tree in syntaxTrees)
        {
            // 获取语法树的根节点
            var root = tree.GetRoot();

            // 获取当前语法树中的所有命名空间节点
            var namespaces = root.DescendantNodes().OfType<NamespaceDeclarationSyntax>();

            // 判断语法树是否在指定检测的命名空间下
            if (namespaces.All(ns => !Definition.TargetNameSpaces.Contains(ns.Name.ToString())))
            {
                continue;
            }

            var enums = GetMatchEnums(root);

            foreach (var enumNode in enums)
            {
                var scriptContent = GenerateFrameSpritePool(enumNode);
                context.AddSource($"FrameSpritePool_Gen.g.cs", scriptContent);
            }
        }
    }

    private string GenerateFrameSpritePool(EnumDeclarationSyntax enumNode)
    {
        var sb = new StringBuilder();
        var enumName = enumNode.Identifier.Text;
        var enumMembers = enumNode.Members;

        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// \tThis code was generated by the source generator.");
        sb.AppendLine("// \tChanges to this file may cause incorrect behavior.");
        sb.AppendLine("// \twill be lost if the code is regenerated.");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine();

        foreach (var usingNameSpace in Definition.UsingNameSpace)
        {
            sb.AppendLine($"using {usingNameSpace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {Definition.NameSpace}");
        {
            sb.AppendLine("{");
            sb.AppendLine($"\tpublic partial class FrameSpritePool : MonoBehaviour");
            {
                sb.AppendLine("\t{");

                // 生成字段
                foreach (var member in enumMembers)
                {
                    var memberName = member.Identifier.Text;
                    var fieldName = char.ToUpper(memberName[0]) + memberName.Substring(1);
                    sb.AppendLine($"\t\tpublic List<Sprite> {fieldName} = new List<Sprite>();");
                }

                sb.AppendLine();
                sb.AppendLine($"\t\tpublic List<Sprite> GetSprites({enumName} animName)");
                {
                    sb.AppendLine("\t\t{");
                    sb.AppendLine("\t\t\tList<Sprite> ret = null;");
                    sb.AppendLine("\t\t\tswitch (animName)");
                    {
                        sb.AppendLine("\t\t\t{");

                        foreach (var member in enumMembers)
                        {
                            var memberName = member.Identifier.Text;
                            var fieldName = char.ToUpper(memberName[0]) + memberName.Substring(1);
                            sb.AppendLine($"\t\t\t\tcase {enumName}.{memberName}:");
                            sb.AppendLine($"\t\t\t\t\tret = {fieldName};");
                            sb.AppendLine("\t\t\t\t\tbreak;");
                        }

                        sb.AppendLine("\t\t\t}");
                    }
                    sb.AppendLine("\t\t\treturn ret;");
                    sb.AppendLine("\t\t}");
                }

                sb.AppendLine();
                sb.AppendLine($"\t\tpublic void AddSprite({enumName} animName, Sprite sprite)");
                {
                    sb.AppendLine("\t\t{");
                    sb.AppendLine("\t\t\tvar list = GetSprites(animName);");
                    sb.AppendLine("\t\t\tlist?.Add(sprite);");
                    sb.AppendLine("\t\t}");
                }

                sb.AppendLine();
                sb.AppendLine("\t\tpublic void SortAllSprites()");
                {
                    sb.AppendLine("\t\t{");

                    foreach (var member in enumMembers)
                    {
                        var memberName = member.Identifier.Text;
                        var fieldName = char.ToUpper(memberName[0]) + memberName.Substring(1);
                        sb.AppendLine($"\t\t\tSortSprite({fieldName});");
                    }

                    sb.AppendLine("\t\t}");
                }

                sb.AppendLine();
                sb.AppendLine("\t\tpublic void SortSprite(List<Sprite> sprites)");
                {
                    sb.AppendLine("\t\t{");
                    sb.AppendLine("\t\t\tsprites.Sort((a, b) =>");
                    sb.AppendLine("\t\t\t{");
                    sb.AppendLine("\t\t\t\tint aNum = ParseLastNumber(a.name);");
                    sb.AppendLine("\t\t\t\tint bNum = ParseLastNumber(b.name);");
                    sb.AppendLine("\t\t\t\treturn aNum.CompareTo(bNum);");
                    sb.AppendLine("\t\t\t});");
                    sb.AppendLine("\t\t}");
                }

                sb.AppendLine();
                sb.AppendLine("\t\tprivate int ParseLastNumber(ReadOnlySpan<char> spriteName)");
                {
                    sb.AppendLine("\t\t{");
                    sb.AppendLine("\t\t\tint lastUnderscore = spriteName.LastIndexOf('_');");
                    sb.AppendLine("\t\t\tif (lastUnderscore < 0) return 0;");
                    sb.AppendLine("\t\t\tvar numberSpan = spriteName.Slice(lastUnderscore + 1);");
                    sb.AppendLine("\t\t\treturn int.TryParse(numberSpan, out int result) ? result : 0;");
                    sb.AppendLine("\t\t}");
                }

                sb.AppendLine("\t}");
            }
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// 获取匹配的枚举声明语法
    /// </summary>
    /// <param name="root"></param>
    /// <returns></returns>
    private IEnumerable<EnumDeclarationSyntax> GetMatchEnums(SyntaxNode root)
        => root.DescendantNodes().OfType<EnumDeclarationSyntax>()
            .Where(e => e.Identifier.Text.ToString().Equals(Definition.EnumName));

    #endregion
}